#!/bin/bash

gitAddress="https://gitlab.com/cit2420/2420-as2-starting-files.git"
gitFolder="2420-as2-starting-files"

if [[ -d ./$gitFolder ]] ; then
  echo "repositories exist!"
else
  git clone $gitAddress
  if [[ -d ./$gitFolder ]] ; then
    echo "git repository ${gitAddress} has been successfully cloned!"
  else
    echo "clone failed!"
fi




