#!/bin/bash

# 'gitClone' script does:
#   - It will clone the given git repository.

# 'gitAddress' stores the https link of the given git repository.
# 'gitFolder' stores the name of the directory that is created when clone the repository. 
gitAddress="https://gitlab.com/cit2420/2420-as2-starting-files.git"
gitFolder="2420-as2-starting-files"

# If the given folder is exist.
# - print that is exist.
# If not exist:
# - do 'git clone $gitAddress'
# - and check it again that the folder is exist.
# - if yes, print it is success.
# - if not, print it is failed.
if [[ -d ./$gitFolder ]] ; then
  echo "repositories exist!"
else
  git clone $gitAddress
  if [[ -d ./$gitFolder ]] ; then
    echo "git repository ${gitAddress} has been successfully cloned!"
  else
    echo "clone failed!"
fi




