#!/bin/bash

# 'main' script does:
#   - It will call two scripts:
#     - the script 'configRepo' does: 
#       - cloning git repository and creating symbolic links.
#     - the script 'installPackage' does: 
#       - install packages list from the given file.
#   - User can call each script with following options:
#     -i: install packages in the file.
#        - argument should be provided for the filename.
#     -c: clone the repository and config the symbolic links. 
#        - argument should be provided for the username.

# Initial checking for error handling. 
# check if the user run this script with sudo previlege.
# check if any option is given
# check if options start with '-'. 
# reference:
# - https://unix.stackexchange.com/questions/50563/how-can-i-detect-that-no-options-were-passed-with-getopts
# - https://stackoverflow.com/questions/18215973/how-to-check-if-running-as-root-in-a-bash-script
if [[ "$(id -u)" -ne 0 ]]; then
    echo "sudo privilege is required to run this script!"
    exit 1
elif [[ $# -eq 0 ]]; then
    echo "Options should be provided!"
    echo "-i (argument: FILENAME): install packages from the file [FILENAME]."
    echo "-c (argument: USERNAME): clone git repository to the [USERNAME]'s directory and create symbolic links."
    exit 1
elif [[ $@ != -* ]]; then
    echo "Options should start with '-'!"
    echo "-i (argument: FILENAME): install packages from the file [FILENAME]."
    echo "-c (argument: USERNAME): clone git repository to the [USERNAME]'s directory and create symbolic links."
    exit 1
fi
# if the script run without sudo previlege:
# - by checking the user id of who execute the script is 0 (always reserved for a root user) or else.
# - if not, print that user need sudo privilege.
# - exit script with exit code 1.
# else if no options are given: 
# - by cheking number of given parameter is 0 or not
# - print that option should be provided.
# - print option usage guide.
# - exit script with exit code 1.
# else if given parameter does not follow correct syntax:
# - which means that does not start with '-'
# - print that option format is wrong.
# - print option usage guide.
# - exit script with exit code 1.

# Give users option to run script that they want.
# Provide default error handling with getopts and case.
while getopts "i:c:" opt; do
  case $opt in
    i)
        ./installPackage "${OPTARG}" || exit 1
    ;;
    c)
        ./configRepo "${OPTARG}" || exit 1
    ;;
    ?)
        exit 1
    ;;  
  esac
done
# use 'getopts' to give two options 'i' and 'c'.
# - make all of them require arguments with ':'.
# - for the case the option is 'i':
#   - Call the script 'installPackage' and run it with provided argument as a file name.
#   - if calling script does not success, exit script with exit code 1.
#   - each error cases will be explained within the script 'installPackage'
# - for the case the option is 'c':
#   - Call the script 'ConfigRepo' and run it with provided argument as a user name.
#   - if calling script does not success, exit script with exit code 1.
#   - each error cases will be explained within the script 'ConfigRepo'
# - for the any other one letter options:
# - It will generate default error messages and exit with exit code 1.